import type { ListDefinition } from '../lib/graphAdmin.js';

export const opportunityList: ListDefinition = {
  displayName: 'TSS_Opportunity',
  description: 'Sales opportunities and deals',
  columns: [
    {
      name: 'tss_opportunityId',
      displayName: 'Opportunity ID',
      type: 'text',
      required: true,
      indexed: true,
    },
    {
      name: 'tss_companyId',
      displayName: 'Company',
      type: 'lookup',
      required: true,
      indexed: true,
      lookupListName: 'TSS_Company',
      lookupColumnName: 'Title',
    },
    {
      name: 'tss_primaryContactId',
      displayName: 'Primary Contact',
      type: 'lookup',
      lookupListName: 'TSS_Contact',
      lookupColumnName: 'Title',
    },
    {
      name: 'tss_stage',
      displayName: 'Stage',
      type: 'choice',
      required: true,
      indexed: true,
      choices: [
        'Lead',
        'Qualification',
        'Quotation',
        'Negotiation',
        'Close',
        'After Action',
      ],
    },
    {
      name: 'tss_closeStatus',
      displayName: 'Close Status',
      type: 'choice',
      indexed: true,
      choices: ['Won', 'Lost', 'Cancelled'],
    },
    {
      name: 'tss_closeReason',
      displayName: 'Close Reason',
      type: 'note',
    },
    {
      name: 'tss_probability',
      displayName: 'Probability (%)',
      type: 'number',
    },
    {
      name: 'tss_revenue',
      displayName: 'Revenue',
      type: 'currency',
    },
    {
      name: 'tss_bidDueDate',
      displayName: 'Bid Due Date',
      type: 'dateTime',
      indexed: true,
    },
    {
      name: 'tss_deliveryDate',
      displayName: 'Delivery Date',
      type: 'dateTime',
    },
    {
      name: 'tss_closeDate',
      displayName: 'Close Date',
      type: 'dateTime',
      indexed: true,
    },
    {
      name: 'tss_owner',
      displayName: 'Owner',
      type: 'text',
      required: true,
      indexed: true,
    },
    {
      name: 'tss_productLine',
      displayName: 'Product Line',
      type: 'choice',
      indexed: true,
      choices: [
        'Well Intervention',
        'New Completions',
        'Green Energy',
        'Engineering Service',
        'Testing Service',
      ],
    },
    {
      name: 'tss_basin',
      displayName: 'Basin/Region',
      type: 'choice',
      choices: [
        'Permian',
        'Eagle Ford',
        'DJ Basin',
        'Bakken',
        'GoM',
        'Marcellus',
        'International',
        'Other',
      ],
    },
    {
      name: 'tss_isRelated',
      displayName: 'Is Related',
      type: 'boolean',
    },
    {
      name: 'tss_relatedOpportunityId',
      displayName: 'Related Opportunity',
      type: 'lookup',
      lookupListName: 'TSS_Opportunity',
      lookupColumnName: 'Title',
    },
    {
      name: 'tss_pursuitDecision',
      displayName: 'Pursuit Decision',
      type: 'choice',
      choices: ['Pursue', 'No-Bid', 'Pending'],
    },
    {
      name: 'tss_pursuitRationale',
      displayName: 'Pursuit Rationale',
      type: 'note',
    },
    {
      name: 'tss_poNumber',
      displayName: 'PO Number',
      type: 'text',
    },
    {
      name: 'tss_isTaxExempt',
      displayName: 'Tax Exempt',
      type: 'boolean',
    },
    {
      name: 'tss_taxDocumentLink',
      displayName: 'Tax Document Link',
      type: 'text',
    },
    {
      name: 'tss_notes',
      displayName: 'Notes',
      type: 'note',
    },
  ],
};
